import type { Metadata } from "next";
import Link from "next/link";
import { getGuidesByLane, type GuideLane } from "@/lib/guideRegistry";
import styles from "./guides-index.module.css";

const SITE = "https://prestoncannabis.com";
const CANONICAL = `${SITE}/guides`;
export const metadata: Metadata = { title: { absolute: "Guides | Preston Cannabis" }, description: "Browse Preston Cannabis name guides for strains, Native Cigarettes, Nicotine Vape, and THC Vape, then check today's menu. Adults 19+.", alternates: { canonical: CANONICAL }, robots: { index: true, follow: true }, openGraph: { title: "Guides | Preston Cannabis", url: CANONICAL } };
const laneCtas: Record<GuideLane, { href: string; label: string }> = { strain: { href: "/menu", label: "View today's flower board" }, native_cig: { href: "/menu/cigarettes", label: "View today's cigarette board" }, nic_vape: { href: "/menu/nicotine-vapes", label: "View today's nicotine vape board" }, thc_vape: { href: "/menu/vape-disposables", label: "View today's THC vape board" } };
const jsonLd = { "@context": "https://schema.org", "@graph": [{ "@type": "WebPage", "@id": `${CANONICAL}#webpage`, url: CANONICAL, name: "Guides | Preston Cannabis", isPartOf: { "@id": `${SITE}/#website` } }, { "@type": "BreadcrumbList", itemListElement: [{ "@type": "ListItem", position: 1, name: "Home", item: SITE }, { "@type": "ListItem", position: 2, name: "Guides", item: CANONICAL }] }] };
export default function GuidesPage() { const groups = getGuidesByLane().filter((group) => group.guides.length); return <main id="main" className={styles.main}><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd).replace(/</g, "\\u003c") }}/><header className={styles.hero}><div className={styles.shell}><nav className={styles.breadcrumb}><Link href="/">Home</Link><span>/</span><span>Guides</span></nav><p className={styles.eyebrow}>Preston name guides</p><h1>Guides | Preston Cannabis</h1><p>Find a name, confirm its shelf, and continue to today&apos;s board. Selection rotates, so these adult 19+ guides provide context without promising availability.</p><div className={styles.actions}><Link href="/menu">Open today&apos;s menu</Link><Link href="/resources">Browse resources</Link></div></div></header><div className={`${styles.shell} ${styles.groups}`}>{groups.map((group) => <section key={group.lane}><div className={styles.groupHead}><div><small>{group.guides.length} name guides</small><h2>{group.label}</h2></div><Link href={laneCtas[group.lane].href}>{laneCtas[group.lane].label}</Link></div><div className={styles.grid}>{group.guides.map((guide) => <Link key={guide.slug} href={`/guides/${guide.slug}`}><strong>{guide.name}</strong><span>Read {group.label} guide</span></Link>)}</div></section>)}</div><aside className={`${styles.shell} ${styles.cta}`}><h2>Check today&apos;s board</h2><p>Use the current menu before travelling to Preston Street.</p><div className={styles.actions}><Link href="/menu">View the menu</Link><Link href="/visit">Plan your visit</Link></div></aside></main>; }
